# Generated by Django 6.0 on 2025-12-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('mno', models.AutoField(primary_key=True, serialize=False)),
                ('mtitle', models.CharField(max_length=1000)),
                ('mcontent', models.TextField()),
                ('mtype', models.CharField(max_length=2)),
                ('mfile', models.FileField(default='', null=True, upload_to='')),
                ('mhit', models.IntegerField(default=0)),
                ('mdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
