# Generated by Django 6.0 on 2025-12-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtype', models.CharField(max_length=2)),
                ('mtype_desc', models.CharField(max_length=100)),
                ('mdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
