# Generated by Django 6.0 on 2025-12-29 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_magazine_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='mtype',
        ),
        migrations.AddField(
            model_name='magazine',
            name='magazine_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazine.magazine_code'),
        ),
    ]
