# Generated by Django 6.0 on 2025-12-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_remove_magazine_mtype_magazine_magazine_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='mfile',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
